# Версия docker-compose
version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs:/var/log/nginx
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - backend    
  php:
    build: 
      context: ./etc/php
      args: 
        PHP_VERSION: ${PHP_VERSION}
        TZ: ${TZ}
    restart: always
    env_file:
      - ".env" 
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www:/var/www
    networks:
      - backend        
  phpmyadmin:
    image: phpmyadmin:${PHPADMIN_VERSION}
    ports:
      - "8080:80"
    env_file:
      - ".env" 
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysql
    networks:
      - backend    
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql:/var/lib/mysql
    env_file:
      - ".env"  
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend  
networks:  
  backend:  
    name: php_backend
    driver: bridge
